services:
  post-cockpit:
    build: .
    container_name: post-cockpit
    environment:
      PORT: "5010"
      PYTHONUNBUFFERED: "1"
    - OLLAMA_BASE=http://172.31.110.153:11434
    - OLLAMA_MODEL=llama3.1:latest

    ports:
      - "5010:5010"
    restart: unless-stopped